name: GitHub Pages

on:
  push:
    branches:
    - main
  workflow_dispatch:
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions: 
      contents: write
  
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: Dump variables
      run: |
         echo repo name ${{github.event.repository.name}}
         echo repo html url ${{github.event.repository.html_url}}
    
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Build Github Pages Angular Site
      run: npm run build -- --configuration production --base-href https://${{github.actor}}.github.io/${{github.event.repository.name}}/

    - name: Deploy
      if: success()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: dist/${{github.event.repository.name}}
        enable_jekyll: true
